import { Injectable } from '@angular/core';
import { ConsumerIndexing } from './consumerIndexing.model';
import { HttpClient } from '@angular/common/http';
import { MeterInstallation } from './meterInstallation.model';
import { ConsumerIndexingComponent } from './consumer-indexing/consumer-indexing.component';
import { Observable } from 'rxjs';

@Injectable({
  providedIn: 'root'
})
export class CIandMIService {

private baseUrl="http://localhost:8080/api";


// private ciList:ConsumerIndexing[]=[
// {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// },
//  {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// },
//  {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// },
//  {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// },
// {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// },
// {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// },
// {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// },
// {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// },
// {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// },
// {
// Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good',
// }

//   ];



  //MIList 
  private miList:MeterInstallation[]=[
//     { 
//       ConsumerData:{
//       sequence_No :'12345',
// discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good'

//     },
    
//  LT_Pole_Condtion_for_Service_cable:'ok',
//   Is_Armoured_Service_Cable_To_be_Installed:'Yes',
//   Neutral_Availability:'Available',
//   Village_Name:'Pune',
//   Village_Census_code:'410501',
//   Gram_Panchayat:'chakan',
//   Block:'Khed',
//   Majra_Mohalla_Street_Name:'Nashik Road',
//   Old_Meter_Billing_Type:'Net Meter',
//   Scan_Barcode_Sticker_placed_on_Old_Meter:'AEW123456',
//   Old_Meter_Number_MI:'Aew2345',
//   New_Meter_Number:'AEW12345',
//   Mismatch_betwwen_old_meter_number_of_CI_and_MI:true,
//   New_Meter_Billing_Type:'Prepaid',
//   Meter_Communication_Type:'GPRS',
//   Meter_CT_Ratio:'-1/',
//   Meter_PT_Ratio:'1',
//   Line_CT_Ratio:'1/5',
//   Line_PT_Ratio:'5/7',
//   Network_Provider_Name_SIM1:'JioTrue5G',
//   Signal_Strength_SIM1:'-74',
//   Signal_Category_SIM1:'Good',
//   Network_Type1:'WIFI',
//   Network_Provider_Name_SIM2:' ',
//   Signal_Strength_SIM2:' ',
//   Signal_Category_SIM2:' ',
//   Network_Type2:' ',
//   Length_Of_Service_Cable_in_Meter:24,
//   Cable_Type:'4 core',
//   Old_Meter_Current_Kwh_MI:250,
//   Mismatch_Between_Reading_of_CI_and_MI:'Matched',
//   Old_Meter_Current_KVah_MI:234,
//   Old_Meter_Kva_MI:245,
//   New_Meter_Current_KWH:5,
//   New_Meter_current_KVAH:6,
//   New_Meter_Phase:'LTCT',
//   Meter_Installation_Type:'Main Meter',
//   Meter_Box_seal_Number1:'Aew123',
//   Meter_Box_Seal_Number2:'Aew1234',
//   NIC_Card1:'Aew76784897972389',
//   NIC_Card2:' ',
//   NIC_Seal_Number1:'Aew89897',
// NIC_Seal_Type:'Plastic',
// Meter_Body_Seal_Type:'Holography',
// Terminal_Seal_Number1:'AEW87987897',
// Terminal_Seal_Number2 :'AEW4652146',
// Meter_Box_Seal_Type:'Plastic',
// MRN_No:'AEW87989',
// Page_No:'27',
// New_Meter_Manufacturer:'AEW',
// Error_Code_Error_Description:'Erro01-Modem Initialization ',
// latitude:'28.45',
// longitude:'77.07',
// Updated_By:'Shital',
// New_Meter_Installed_Date:new Date(),
// Status:'Approved by Qc contractor',
// QC_Contractor_Approved_Date:new Date(),
// Approved_By_QC_Contractor:'qccontractor@gmail.com',
// IntelliSmart_Approved_Date:new Date(),
// Approved_By_IntelliSmart:' ',
// Discom_Approved_Date: new Date(),
// Approved_By_Discom:' ',
// QC_Contractor_Rejected_Remarks:'ok',
// QC_Contractor_Rejected_Date:new Date(),
// Rejected_By_QC_Contractor:'qccontractor@gmail.com',
// IntelliSmart_Rejected_Remarks:'Please Retake the photo',
// IntelliSmart_Rejected_Date:new Date(),
// IntelliSmar_Rejected_By:'Rejected',
// Discom_Rejected_Remarks:'please take the photos',
// Discom_Rejected_Date:new Date(),
// Rejected_By_Discom:' ',
// No_Of_Rejections:5,
// Area:'Noida',
// CT_Chamber_Seal_No:'AEW123456'

//   },
//   {
//      ConsumerData:{
//       Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good'

//     },
    
//  LT_Pole_Condtion_for_Service_cable:'ok',
//   Is_Armoured_Service_Cable_To_be_Installed:'Yes',
//   Neutral_Availability:'Available',
//   Village_Name:'Pune',
//   Village_Census_code:'410501',
//   Gram_Panchayat:'chakan',
//   Block:'Khed',
//   Majra_Mohalla_Street_Name:'Nashik Road',
//   Old_Meter_Billing_Type:'Net Meter',
//   Scan_Barcode_Sticker_placed_on_Old_Meter:'AEW123456',
//   Old_Meter_Number_MI:'Aew2345',
//   New_Meter_Number:'AEW12345',
//   Mismatch_betwwen_old_meter_number_of_CI_and_MI:true,
//   New_Meter_Billing_Type:'Prepaid',
//   Meter_Communication_Type:'GPRS',
//   Meter_CT_Ratio:'-1/',
//   Meter_PT_Ratio:'1',
//   Line_CT_Ratio:'1/5',
//   Line_PT_Ratio:'5/7',
//   Network_Provider_Name_SIM1:'JioTrue5G',
//   Signal_Strength_SIM1:'-74',
//   Signal_Category_SIM1:'Good',
//   Network_Type1:'WIFI',
//   Network_Provider_Name_SIM2:' ',
//   Signal_Strength_SIM2:' ',
//   Signal_Category_SIM2:' ',
//   Network_Type2:' ',
//   Length_Of_Service_Cable_in_Meter:24,
//   Cable_Type:'4 core',
//   Old_Meter_Current_Kwh_MI:250,
//   Mismatch_Between_Reading_of_CI_and_MI:'Matched',
//   Old_Meter_Current_KVah_MI:234,
//   Old_Meter_Kva_MI:245,
//   New_Meter_Current_KWH:5,
//   New_Meter_current_KVAH:6,
//   New_Meter_Phase:'LTCT',
//   Meter_Installation_Type:'Main Meter',
//   Meter_Box_seal_Number1:'Aew123',
//   Meter_Box_Seal_Number2:'Aew1234',
//   NIC_Card1:'Aew76784897972389',
//   NIC_Card2:' ',
//   NIC_Seal_Number1:'Aew89897',
// NIC_Seal_Type:'Plastic',
// Meter_Body_Seal_Type:'Holography',
// Terminal_Seal_Number1:'AEW87987897',
// Terminal_Seal_Number2 :'AEW4652146',
// Meter_Box_Seal_Type:'Plastic',
// MRN_No:'AEW87989',
// Page_No:'27',
// New_Meter_Manufacturer:'AEW',
// Error_Code_Error_Description:'Erro01-Modem Initialization ',
// latitude:'28.45',
// longitude:'77.07',
// Updated_By:'Shital',
// New_Meter_Installed_Date:new Date(),
// Status:'Approved by Qc contractor',
// QC_Contractor_Approved_Date:new Date(),
// Approved_By_QC_Contractor:'qccontractor@gmail.com',
// IntelliSmart_Approved_Date:new Date(),
// Approved_By_IntelliSmart:' ',
// Discom_Approved_Date: new Date(),
// Approved_By_Discom:' ',
// QC_Contractor_Rejected_Remarks:'ok',
// QC_Contractor_Rejected_Date:new Date(),
// Rejected_By_QC_Contractor:'qccontractor@gmail.com',
// IntelliSmart_Rejected_Remarks:'Please Retake the photo',
// IntelliSmart_Rejected_Date:new Date(),
// IntelliSmar_Rejected_By:'Rejected',
// Discom_Rejected_Remarks:'please take the photos',
// Discom_Rejected_Date:new Date(),
// Rejected_By_Discom:' ',
// No_Of_Rejections:5,
// Area:'Noida',
// CT_Chamber_Seal_No:'AEW123456'

//   },
//   {
//      ConsumerData:{
//       Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good'

//     },
    
//  LT_Pole_Condtion_for_Service_cable:'ok',
//   Is_Armoured_Service_Cable_To_be_Installed:'Yes',
//   Neutral_Availability:'Available',
//   Village_Name:'Pune',
//   Village_Census_code:'410501',
//   Gram_Panchayat:'chakan',
//   Block:'Khed',
//   Majra_Mohalla_Street_Name:'Nashik Road',
//   Old_Meter_Billing_Type:'Net Meter',
//   Scan_Barcode_Sticker_placed_on_Old_Meter:'AEW123456',
//   Old_Meter_Number_MI:'Aew2345',
//   New_Meter_Number:'AEW12345',
//   Mismatch_betwwen_old_meter_number_of_CI_and_MI:true,
//   New_Meter_Billing_Type:'Prepaid',
//   Meter_Communication_Type:'GPRS',
//   Meter_CT_Ratio:'-1/',
//   Meter_PT_Ratio:'1',
//   Line_CT_Ratio:'1/5',
//   Line_PT_Ratio:'5/7',
//   Network_Provider_Name_SIM1:'JioTrue5G',
//   Signal_Strength_SIM1:'-74',
//   Signal_Category_SIM1:'Good',
//   Network_Type1:'WIFI',
//   Network_Provider_Name_SIM2:' ',
//   Signal_Strength_SIM2:' ',
//   Signal_Category_SIM2:' ',
//   Network_Type2:' ',
//   Length_Of_Service_Cable_in_Meter:24,
//   Cable_Type:'4 core',
//   Old_Meter_Current_Kwh_MI:250,
//   Mismatch_Between_Reading_of_CI_and_MI:'Matched',
//   Old_Meter_Current_KVah_MI:234,
//   Old_Meter_Kva_MI:245,
//   New_Meter_Current_KWH:5,
//   New_Meter_current_KVAH:6,
//   New_Meter_Phase:'LTCT',
//   Meter_Installation_Type:'Main Meter',
//   Meter_Box_seal_Number1:'Aew123',
//   Meter_Box_Seal_Number2:'Aew1234',
//   NIC_Card1:'Aew76784897972389',
//   NIC_Card2:' ',
//   NIC_Seal_Number1:'Aew89897',
// NIC_Seal_Type:'Plastic',
// Meter_Body_Seal_Type:'Holography',
// Terminal_Seal_Number1:'AEW87987897',
// Terminal_Seal_Number2 :'AEW4652146',
// Meter_Box_Seal_Type:'Plastic',
// MRN_No:'AEW87989',
// Page_No:'27',
// New_Meter_Manufacturer:'AEW',
// Error_Code_Error_Description:'Erro01-Modem Initialization ',
// latitude:'28.45',
// longitude:'77.07',
// Updated_By:'Shital',
// New_Meter_Installed_Date:new Date(),
// Status:'Approved by Qc contractor',
// QC_Contractor_Approved_Date:new Date(),
// Approved_By_QC_Contractor:'qccontractor@gmail.com',
// IntelliSmart_Approved_Date:new Date(),
// Approved_By_IntelliSmart:' ',
// Discom_Approved_Date: new Date(),
// Approved_By_Discom:' ',
// QC_Contractor_Rejected_Remarks:'ok',
// QC_Contractor_Rejected_Date:new Date(),
// Rejected_By_QC_Contractor:'qccontractor@gmail.com',
// IntelliSmart_Rejected_Remarks:'Please Retake the photo',
// IntelliSmart_Rejected_Date:new Date(),
// IntelliSmar_Rejected_By:'Rejected',
// Discom_Rejected_Remarks:'please take the photos',
// Discom_Rejected_Date:new Date(),
// Rejected_By_Discom:' ',
// No_Of_Rejections:5,
// Area:'Noida',
// CT_Chamber_Seal_No:'AEW123456'

//   },
// {
//    ConsumerData:{
//       Sequence_No :'12345',
// Discom : 'MVVNL',
// Zone: 'LESA TRANS',
// Circle:'EUDC',
// Division:'EUDI',
// Sub_Division:'AHIBARANPUR',
// Substation_Code:'AHIBARANPUR1234',
// Feeder_Name:'123567654',
// Consumer_Number:'12345' ,
// Landmark:'Shiv Nagar',
// Consumer_Name:'Nilesh Kumkar',
// Address:'Sukhrali ',
// Area:'near fitness gym ',
// Mobile_Number:'918976567898',
// Email_ID:'nilesh@gmail.com',
// Billing_Type:'NetMetering',
// Old_Meter_Number:'AEW1234',
// Old_Meter_Manufacturer:'AEW',
// Load_Unit:230,
// Meter_Location:'basement',
// Old_Meter_Status:'Ok',
// Old_meter_Current_Kva_CI:240,
// Old_meter_Current_Kvah_CI:342,
// Old_meter_Current_Kwh_CI:250,
// Old_Meter_Phase:212,
// Survey_done_by:'shweta',
// Contractor_Name:'contractor',
// CI_Date:new Date(),
// CI_Remarks:'Good'

//     },
    
//  LT_Pole_Condtion_for_Service_cable:'ok',
//   Is_Armoured_Service_Cable_To_be_Installed:'Yes',
//   Neutral_Availability:'Available',
//   Village_Name:'Pune',
//   Village_Census_code:'410501',
//   Gram_Panchayat:'chakan',
//   Block:'Khed',
//   Majra_Mohalla_Street_Name:'Nashik Road',
//   Old_Meter_Billing_Type:'Net Meter',
//   Scan_Barcode_Sticker_placed_on_Old_Meter:'AEW123456',
//   Old_Meter_Number_MI:'Aew2345',
//   New_Meter_Number:'AEW12345',
//   Mismatch_betwwen_old_meter_number_of_CI_and_MI:true,
//   New_Meter_Billing_Type:'Prepaid',
//   Meter_Communication_Type:'GPRS',
//   Meter_CT_Ratio:'-1/',
//   Meter_PT_Ratio:'1',
//   Line_CT_Ratio:'1/5',
//   Line_PT_Ratio:'5/7',
//   Network_Provider_Name_SIM1:'JioTrue5G',
//   Signal_Strength_SIM1:'-74',
//   Signal_Category_SIM1:'Good',
//   Network_Type1:'WIFI',
//   Network_Provider_Name_SIM2:' ',
//   Signal_Strength_SIM2:' ',
//   Signal_Category_SIM2:' ',
//   Network_Type2:' ',
//   Length_Of_Service_Cable_in_Meter:24,
//   Cable_Type:'4 core',
//   Old_Meter_Current_Kwh_MI:250,
//   Mismatch_Between_Reading_of_CI_and_MI:'Matched',
//   Old_Meter_Current_KVah_MI:234,
//   Old_Meter_Kva_MI:245,
//   New_Meter_Current_KWH:5,
//   New_Meter_current_KVAH:6,
//   New_Meter_Phase:'LTCT',
//   Meter_Installation_Type:'Main Meter',
//   Meter_Box_seal_Number1:'Aew123',
//   Meter_Box_Seal_Number2:'Aew1234',
//   NIC_Card1:'Aew76784897972389',
//   NIC_Card2:' ',
//   NIC_Seal_Number1:'Aew89897',
// NIC_Seal_Type:'Plastic',
// Meter_Body_Seal_Type:'Holography',
// Terminal_Seal_Number1:'AEW87987897',
// Terminal_Seal_Number2 :'AEW4652146',
// Meter_Box_Seal_Type:'Plastic',
// MRN_No:'AEW87989',
// Page_No:'27',
// New_Meter_Manufacturer:'AEW',
// Error_Code_Error_Description:'Erro01-Modem Initialization ',
// latitude:'28.45',
// longitude:'77.07',
// Updated_By:'Shital',
// New_Meter_Installed_Date:new Date(),
// Status:'Approved by Qc contractor',
// QC_Contractor_Approved_Date:new Date(),
// Approved_By_QC_Contractor:'qccontractor@gmail.com',
// IntelliSmart_Approved_Date:new Date(),
// Approved_By_IntelliSmart:' ',
// Discom_Approved_Date: new Date(),
// Approved_By_Discom:' ',
// QC_Contractor_Rejected_Remarks:'ok',
// QC_Contractor_Rejected_Date:new Date(),
// Rejected_By_QC_Contractor:'qccontractor@gmail.com',
// IntelliSmart_Rejected_Remarks:'Please Retake the photo',
// IntelliSmart_Rejected_Date:new Date(),
// IntelliSmar_Rejected_By:'Rejected',
// Discom_Rejected_Remarks:'please take the photos',
// Discom_Rejected_Date:new Date(),
// Rejected_By_Discom:' ',
// No_Of_Rejections:5,
// Area:'Noida',
// CT_Chamber_Seal_No:'AEW123456'

//   }

];


constructor(private http:HttpClient) { }

  getAllCI():Observable<ConsumerIndexing[]>{
     return this.http.get<ConsumerIndexing[]>(`${this.baseUrl}/getAllCI`);
    //return this.ciList;
  }

  getAllMI():Observable<MeterInstallation[]>{
           return this.http.get<MeterInstallation[]>(`${this.baseUrl}/getAllMI`);
  }

}
